# Generated by Django 2.1.3 on 2018-11-29 03:46

import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_date', models.DateField(default=datetime.date(2018, 11, 29), verbose_name='时间')),
                ('job_isover', models.BooleanField(default=False, verbose_name='是否完成')),
                ('job_content', models.TextField(help_text='详细信息', max_length=500, verbose_name='Job')),
                ('job_comment', models.TextField(blank=True, help_text='备注', max_length=500, verbose_name='备注')),
            ],
            options={
                'verbose_name': 'Work',
                'verbose_name_plural': 'Work',
            },
        ),
        migrations.CreateModel(
            name='level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(help_text='事情等级，例：重要紧急', max_length=50, verbose_name='事件等级')),
                ('level_comment', models.TextField(blank=True, help_text='备注', max_length=500, verbose_name='备注')),
            ],
            options={
                'verbose_name': 'Level',
                'verbose_name_plural': 'Level',
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.CharField(help_text='用于接收通知', max_length=20, verbose_name='联系电话')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'User',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='job_level',
            field=models.ForeignKey(help_text='事件等级', on_delete=django.db.models.deletion.CASCADE, to='job.level', verbose_name='Job等级'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_user',
            field=models.ForeignKey(help_text='任务归属', on_delete=django.db.models.deletion.CASCADE, to='job.user', verbose_name='Job归属'),
        ),
    ]
