# Generated by Django 2.1.2 on 2018-10-29 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_date', models.DateField()),
                ('job_content', models.CharField(help_text='详细信息', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(help_text='事情等级，例：重要紧急', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='job_level',
            field=models.ForeignKey(help_text='事情等级', on_delete=django.db.models.deletion.CASCADE, to='job.level'),
        ),
    ]
