# Generated by Django 2.1.2 on 2018-10-29 06:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_content',
            field=models.TextField(help_text='详细信息', max_length=500),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_date',
            field=models.DateField(default=datetime.date(2018, 10, 29)),
        ),
    ]
