# Generated by Django 2.1.2 on 2018-10-29 07:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_job_job_isover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_content',
            field=models.TextField(help_text='详细信息', max_length=500, verbose_name='待做事项'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_date',
            field=models.DateField(default=datetime.date(2018, 10, 29), verbose_name='时间'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_isover',
            field=models.BooleanField(default=False, verbose_name='是否完成'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_level',
            field=models.ForeignKey(help_text='事件等级', on_delete=django.db.models.deletion.CASCADE, to='job.level', verbose_name='事件等级'),
        ),
        migrations.AlterField(
            model_name='level',
            name='level_name',
            field=models.CharField(help_text='事情等级，例：重要紧急', max_length=50, verbose_name='事件等级'),
        ),
    ]
