# Generated by Django 2.1.2 on 2018-10-31 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_auto_20181031_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_comment',
            field=models.TextField(default='', help_text='备注', max_length=500, verbose_name='备注'),
        ),
    ]
