# Generated by Django 2.1.2 on 2018-10-31 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_job_job_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_comment',
            field=models.TextField(help_text='备注', max_length=500, verbose_name='备注'),
        ),
    ]
