# Generated by Django 2.1.2 on 2018-10-31 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_auto_20181031_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_comment',
            field=models.TextField(help_text='备注', max_length=500, null=True, verbose_name='备注'),
        ),
    ]
